AspNetCore_2020_04_20/AspNetCore_MVC_EF/Controllers/PartialViewSamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCore_MVC_EF.Data;
using AspNetCore_MVC_EF.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore_MVC_EF.Controllers
{
    public class PartialViewSamplesController : Controller
    {
        private readonly BlogDbContext _context;

        public PartialViewSamplesController(BlogDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PartialViewBasicSample()
        {
            return View();
        }

        public IActionResult ShowPartialWithViewModel()
        {
            BlogCommentViewModel vm = new BlogCommentViewModel();

            vm.Blogs = _context.Blog.ToList();
            vm.Comments = _context.Comment.ToList();


            return View(vm);
        }

        public IActionResult LoadPartialOverGetMethod()
        {
            return View();
        }

        public IActionResult OnGetMyPartial() =>
            new PartialViewResult
            {
                ViewName = "_Address",
                ViewData = ViewData,
            };



    }
}

AspNetCore_2020_04_20/AspNetCore_MVC_EF/Views/PartialViewSamples/LoadPartialOverGetMethod.cshtml
@{
    ViewData["Title"] = "LoadPartialOverGetMethod";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>LoadPartialOverGetMethod</h1>

<p>Diese Partial View wurde über die Controller.Methode OnGetPartial gerendert</p>
@Html.ActionLink("Zeige weitere PartialView an", "OnGetMyPartial", "PartialViewSamples");



<p>Formular wurde fertig geladen und PartialView wird on the fly via jQuery nachgeladen</p>
<div id="div1"></div>

<p>Magst du ein Button drücken</p>
<button type="button" id="button1">Load Partial View</button>
<div id="div2"></div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script type="text/jscript">
    $(document).ready(function () {
        $("#div2").load('/PartialViewSamples/OnGetMyPartial');
    });

    $("#button1").on("click", function () {
        $("#div1").load("/PartialViewSamples/OnGetMyPartial");
    });
</script>

AspNetCore_2020_04_20/AspNetCore_MVC_EF/Views/PartialViewSamples/PartialViewBasicSample.cshtml
@{
    ViewData["Title"] = "PartialViewBasicSample";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>PartialViewBasicSample</h1>


<partial name="_Zeit" />


@{Html.RenderPartial("_Zeit");}

<!-- Absoluter Pfad zur PartialView-->
@*<partial name="~/Views/Shared/_Address.cshtml" />*@

<!-- relativer Pfad zur PartialView-->
@*<partial name="../Blog/_LinkToBlockView.cshtml" />*@

AspNetCore_2020_04_20/AspNetCore_MVC_EF/Views/PartialViewSamples/ShowPartialWithViewModel.cshtml
@model AspNetCore_MVC_EF.ViewModels.BlogCommentViewModel
@{
    ViewData["Title"] = "ShowPartialWithViewModel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ShowPartialWithViewModel</h1>

<ul>
    @foreach (var item in Model.Blogs)
    {
        <li>
            Titel: @item.Title
        </li>
    }
</ul>

<div>
    <partial name="_ShowComments" />
</div>